// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using WeddingPlanner;

namespace WeddingPlanner.Migrations
{
    [DbContext(typeof(wedding_plannerContext))]
    [Migration("20171031200733_precommit")]
    partial class precommit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("WeddingPlanner.Models.Rsvps", b =>
                {
                    b.Property<int>("RsvpId")
                        .HasColumnName("rsvp_id")
                        .HasColumnType("int(11)");

                    b.Property<int>("GuestId")
                        .HasColumnName("user_id")
                        .HasColumnType("int(11)");

                    b.Property<int>("WeddingId")
                        .HasColumnName("wedding_id")
                        .HasColumnType("int(11)");

                    b.HasKey("RsvpId", "GuestId", "WeddingId");

                    b.HasIndex("GuestId")
                        .HasName("fk_rsvps_users1_idx");

                    b.HasIndex("WeddingId", "GuestId")
                        .HasName("fk_rsvps_weddings1_idx");

                    b.ToTable("rsvps");
                });

            modelBuilder.Entity("WeddingPlanner.Models.Users", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnName("user_id")
                        .HasColumnType("int(11)");

                    b.Property<string>("Email")
                        .HasColumnName("email")
                        .HasMaxLength(45);

                    b.Property<string>("FirstName")
                        .HasColumnName("first_name")
                        .HasMaxLength(45);

                    b.Property<string>("LastName")
                        .HasColumnName("last_name")
                        .HasMaxLength(45);

                    b.Property<string>("Password")
                        .HasColumnName("password")
                        .HasMaxLength(255);

                    b.HasKey("UserId");

                    b.ToTable("users");
                });

            modelBuilder.Entity("WeddingPlanner.Models.Weddings", b =>
                {
                    b.Property<int>("WeddingId")
                        .HasColumnName("wedding_id")
                        .HasColumnType("int(11)");

                    b.Property<int>("GuestId")
                        .HasColumnName("user_id")
                        .HasColumnType("int(11)");

                    b.Property<string>("Address")
                        .HasColumnName("address")
                        .HasMaxLength(100);

                    b.Property<string>("BrideName")
                        .HasColumnName("bride_name")
                        .HasMaxLength(45);

                    b.Property<DateTime?>("Date")
                        .HasColumnName("date")
                        .HasColumnType("datetime");

                    b.Property<string>("GroomName")
                        .HasColumnName("groom_name")
                        .HasMaxLength(45);

                    b.Property<int?>("GuestUserId");

                    b.HasKey("WeddingId", "GuestId");

                    b.HasIndex("GuestId")
                        .HasName("fk_weddings_users_idx");

                    b.HasIndex("GuestUserId");

                    b.ToTable("weddings");
                });

            modelBuilder.Entity("WeddingPlanner.Models.Rsvps", b =>
                {
                    b.HasOne("WeddingPlanner.Models.Users", "Guest")
                        .WithMany("Rsvps")
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WeddingPlanner.Models.Weddings", "Weddings")
                        .WithMany("Guests")
                        .HasForeignKey("WeddingId", "GuestId")
                        .HasConstraintName("fk_rsvps_weddings1");
                });

            modelBuilder.Entity("WeddingPlanner.Models.Weddings", b =>
                {
                    b.HasOne("WeddingPlanner.Models.Users", "User")
                        .WithMany("Weddings")
                        .HasForeignKey("GuestId")
                        .HasConstraintName("fk_weddings_users");

                    b.HasOne("WeddingPlanner.Models.Users", "Guest")
                        .WithMany()
                        .HasForeignKey("GuestUserId");
                });
#pragma warning restore 612, 618
        }
    }
}
