// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using WeddingPlanner;

namespace WeddingPlanner.Migrations
{
    [DbContext(typeof(wedding_plannerContext))]
    [Migration("20171101060243_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("WeddingPlanner.Models.Rsvps", b =>
                {
                    b.Property<int>("RsvpId")
                        .HasColumnName("rsvp_id")
                        .HasColumnType("int(11)");

                    b.Property<int>("UserId")
                        .HasColumnName("user_id")
                        .HasColumnType("int(11)");

                    b.Property<int>("WeddingId")
                        .HasColumnName("wedding_id")
                        .HasColumnType("int(11)");

                    b.Property<int?>("RsvpId1");

                    b.Property<int?>("RsvpUserId");

                    b.Property<int?>("RsvpWeddingId");

                    b.HasKey("RsvpId", "UserId", "WeddingId");

                    b.HasIndex("UserId");

                    b.HasIndex("WeddingId");

                    b.HasIndex("RsvpId1", "RsvpUserId", "RsvpWeddingId");

                    b.ToTable("rsvps");
                });

            modelBuilder.Entity("WeddingPlanner.Models.Users", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnName("user_id")
                        .HasColumnType("int(11)");

                    b.Property<string>("Email")
                        .HasColumnName("email")
                        .HasMaxLength(45);

                    b.Property<string>("FirstName")
                        .HasColumnName("first_name")
                        .HasMaxLength(45);

                    b.Property<string>("LastName")
                        .HasColumnName("last_name")
                        .HasMaxLength(45);

                    b.Property<string>("Password")
                        .HasColumnName("password")
                        .HasMaxLength(255);

                    b.Property<int?>("RsvpsRsvpId");

                    b.Property<int?>("RsvpsUserId");

                    b.Property<int?>("RsvpsWeddingId");

                    b.HasKey("UserId");

                    b.HasIndex("RsvpsRsvpId", "RsvpsUserId", "RsvpsWeddingId");

                    b.ToTable("users");
                });

            modelBuilder.Entity("WeddingPlanner.Models.Weddings", b =>
                {
                    b.Property<int>("WeddingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("wedding_id")
                        .HasColumnType("int(11)");

                    b.Property<string>("Address")
                        .HasColumnName("address")
                        .HasMaxLength(100);

                    b.Property<string>("BrideName")
                        .HasColumnName("bride_name")
                        .HasMaxLength(45);

                    b.Property<DateTime?>("Date")
                        .HasColumnName("date")
                        .HasColumnType("datetime");

                    b.Property<string>("GroomName")
                        .HasColumnName("groom_name")
                        .HasMaxLength(45);

                    b.Property<int?>("RsvpsRsvpId");

                    b.Property<int?>("RsvpsUserId");

                    b.Property<int?>("RsvpsWeddingId");

                    b.Property<int>("UserId")
                        .HasColumnName("user_id")
                        .HasColumnType("int(11)");

                    b.HasKey("WeddingId");

                    b.HasIndex("UserId");

                    b.HasIndex("RsvpsRsvpId", "RsvpsUserId", "RsvpsWeddingId");

                    b.ToTable("weddings");
                });

            modelBuilder.Entity("WeddingPlanner.Models.Rsvps", b =>
                {
                    b.HasOne("WeddingPlanner.Models.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WeddingPlanner.Models.Weddings", "Wedding")
                        .WithMany()
                        .HasForeignKey("WeddingId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WeddingPlanner.Models.Rsvps", "Rsvp")
                        .WithMany()
                        .HasForeignKey("RsvpId1", "RsvpUserId", "RsvpWeddingId");
                });

            modelBuilder.Entity("WeddingPlanner.Models.Users", b =>
                {
                    b.HasOne("WeddingPlanner.Models.Rsvps")
                        .WithMany("Users")
                        .HasForeignKey("RsvpsRsvpId", "RsvpsUserId", "RsvpsWeddingId");
                });

            modelBuilder.Entity("WeddingPlanner.Models.Weddings", b =>
                {
                    b.HasOne("WeddingPlanner.Models.Users", "User")
                        .WithMany("Weddings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WeddingPlanner.Models.Rsvps")
                        .WithMany("Weddings")
                        .HasForeignKey("RsvpsRsvpId", "RsvpsUserId", "RsvpsWeddingId");
                });
#pragma warning restore 612, 618
        }
    }
}
